# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nicholas Matsumoto
title: Student
email: matsumon@oregonstate.edu
website: https://matsumon.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  matsumon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: nicholas-matsumoto-60546a1b9
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I am currently looking for an internship/job that will help grow my skills as a software developer.

 Useful Skills: 
 <mark>C/C++</mark>
 <mark>Javascript/Typescript</mark>
 <mark>Html</mark>
 <mark>CSS</mark>
 <mark>SQL</mark>
 <mark>Typeorm</mark>
 <mark>Apollo Client</mark>
 <mark>Apollo Server</mark>
 <mark>Apollo Federation</mark>
 <mark>React</mark>
 <mark>AntD</mark>
 <mark>Blueprint</mark>
 <mark>Cron</mark>
 <mark>Axios</mark>
 <mark>Emotion</mark>
 <mark>Lodash</mark>
 <mark>Git</mark>
 <mark>Vim</mark>
 <mark>Visual Studio</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: TTT-Language-Interpreter
        link: github.com/matsumon
        # link_text: Project Website
        additional_links:
          - title:  matsumon/TTT-Language-Interpreter
            icon: fab fa-github
            url: https://github.com/matsumon/TTT-Language-Interpreter
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A pass by imperative language that includes first-class functions and list operations.
      - layout: top-left
        title: Small Shell
        link: github.com/matsumon
        # link_text: Project Website
        additional_links:
          - title:  matsumon/smallShell
            icon: fab fa-github
            url: https://github.com/matsumon/smallshell
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A bash shell emulator.
      - layout: top-left
        title: Workout Tracker
        link: github.com/matsumon
        # link_text: Project Website
        additional_links:
          - title:  matsumon/workoutTracker
            icon: fab fa-github
            url: https://github.com/matsumon/CS290Final-Project
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A workout tracker that provides 1-rep estimates and charts a users progress using google charts.
      - layout: top-left
        title: Betchya
        link: https://www.betchya.io/
        # link_text: Project Website
        additional_links:
          - title:  Betchya
            icon: fab fa-github
            url: https://www.betchya.io/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Betchya is a mobile sports betting application that allows users to place various types of bets such as prop and line betting.
          This project utilized many different technologies such as: Firestore, Google Admob, NoSQL, SQL, Flutter, Dart, and Javascript.
          I have developed a variety of features for this project which include: 1) An age verification check, 2) Win/Loss/Tie tag for bets, and 3) Implemented 
          a transactional ledger that tracks in-game currency and actual money. In collaboration with another teammate, we developed a system to deliver interstitial and banner ads to users.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Garmin AT 
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Web Dev Intern
        caption: March 2020 - September 2020
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Improved a preexisting circuit board tracking software by rewriting the tool to use new technologies and faster SQL queries resulting in a smoother user experience

            Created a scheduler that interacted with multiple other programs to autonomously schedule maintenance tasks in a project tracking software, while tracking important machine data that would inform future purchase decisions
      - layout: left
        title: Jamba Juice
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Shift Manager
        caption: March 2010 - March 2015
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Responsible for accounting, store promotions, guest complaints, team member training/coaching, and catering
            Reached multiple challenging sale goals by coaching team members, which resulted in record high sales
      - layout: left
        title: Hilton Garden Inn
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Houseperson
        caption: May 2015 - March 2020
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Handled guest complaints/requests, fixed mechanical issues, and maintained general hotel areas
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Oregon State University
        caption: 2015 - present
        sub_title: BSc Computer Science

  - title: Clubs
    layout: text
    content: | # this will include new lines to allow paragraphs
      Robotics Club, Aviation:  Developed part of the software that will direct an autonomous flying drone using a computervision library, OpenCV
      
      Linux Users Group
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
  - title: Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hilton Garden Inn Employee of the Year  2016

      Jamba Juice Sales Competition 2011-2014
      
      1st place at DECA, city-wide business competition 2012
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
